export const GET_SPARQL_DATA = 'GET_SPARQL_DATA';
export const GET_DATA_FROM_PROVIDER = 'GET_DATA_FROM_PROVIDER';
export const SET_CONNECTED_DATA_PARAMETERS = 'SET_CONNECTED_DATA_PARAMETERS';
export const DELETE_CONNECTED_DATA_PARAMETERS =
  'DELETE_CONNECTED_DATA_PARAMETERS';
export const CHANGE_SIDEBAR_STATE = 'CHANGE_SIDEBAR_STATE';

export const DATA_PROVIDER_TYPES = [
  'forests.content.interfaces.IBasicDataProvider',
  'eea.restapi.interfaces.IBasicDataProvider',
];

export const DATACONNECTOR_PARAMS_GROUP = 'DataConnector Parameter';
export const GET_DISCODATA_RESOURCE = 'GET_DISCODATA_RESOURCE';
export const SET_DISCODATA_RESOURCE = 'SET_DISCODATA_RESOURCE';
export const SET_DISCODATA_RESOURCE_PENDING = 'SET_DISCODATA_RESOURCE_PENDING';
export const SET_DISCODATA_QUERY = 'SET_DISCODATA_QUERY';
export const SET_QUERY_PARAM = 'SET_QUERY_PARAM';
export const DELETE_QUERY_PARAM = 'DELETE_QUERY_PARAM';
export const TRIGGER_RENDER = 'TRIGGER_RENDER';
