export const GET_BLOCKDATA = 'GET_BLOCKDATA';
export const GET_SPARQL_DATA = 'GET_SPARQL_DATA';
export const GET_DATA_FROM_PROVIDER = 'GET_DATA_FROM_PROVIDER';
export const SET_PROVIDER_CONTENT = 'SET_PROVIDER_CONTENT';
export const SET_CONNECTED_DATA_PARAMETERS = 'SET_CONNECTED_DATA_PARAMETERS';
export const DELETE_CONNECTED_DATA_PARAMETERS =
  'DELETE_CONNECTED_DATA_PARAMETERS';
export const CHANGE_SIDEBAR_STATE = 'CHANGE_SIDEBAR_STATE';

export const DATA_PROVIDER_TYPES = [
  'forests.content.interfaces.IBasicDataProvider',
  'eea.restapi.interfaces.IBasicDataProvider',
];

export const DATACONNECTOR_PARAMS_GROUP = 'DataConnector Parameter';
export const SET_ROUTE_PARAMETER = 'SET_ROUTE_PARAMETER';
export const DELETE_ROUTE_PARAMETER = 'DELETE_ROUTE_PARAMETER';
